version: '3'
services:
### cadvisor ####################################################
    cadvisor:
      build:
        context: ./cadvisor
      ports:
        - "8080:8080"
      command: -storage_driver=influxdb -storage_driver_db=docker -storage_driver_host=192.168.3.51:8086 -storage_driver_user=admin -storage_driver_password=admin
      privileged: true
      volumes:
        - /:/rootfs:ro
        - /sys:/sys:ro
        - /var/run:/var/run:rw
        - /var/lib/docker/:/var/lib/docker:ro
### node-exporter ####################################################
    node-exporter:
      build:
        context: ./node-exporter
      restart: always
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "5"
      ports:
        - 9100:9100
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      command:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/devicemapper|rootfs/var/lib/docker/aufs)($$|/)'